services:
  caddy:
    image: caddy:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./conf:/etc/caddy
      - caddy_data:/data
      - caddy_config:/config
    cap_add:
      - NET_ADMIN
    depends_on:
      - streamlit
    networks:
      - appnet

  streamlit:
    build: .
    container_name: streamlit
    restart: unless-stopped
    expose:
      - "8501"
    networks:
      - appnet

volumes:
  caddy_data:
  caddy_config:

networks:
  appnet:
    driver: bridge